### ISSUE TITLE
Hmmm

### ISSUE THREAD

**Issue by note3crafter** [Julicraft44/PayAll#1]
https://github.com/note3crafter/Core-V5/blob/main/src/TheNote/core/command/PayallCommand.php

Kann es sein das du da abgeschaut hast :) ?

**Comment by Julicraft44** [comment]
Nein. Habe ich nicht. Ich schreibe meine Plugins für gewöhlich selber :)

**Comment by note3crafter** [comment]
https://github.com/Leonxv/Payall/blob/master/src/Aleondev/payall/Main.php

ist aber nur komisch das es genau gleich ausschaut... nur paar sachen anders genannt und alles in die config übertragen ist nicht grade schön... da der leon und ich beide es von xxflow bekommen hatten... aber nachmachen ist nicht schön...
